import type { Account, AccountAnalysis, DocumentRow, Extraction } from '@/lib/types'
import { DOC_TYPE_LABELS } from '@/lib/types'

export function buildExtractionsCsv(
  account: Account,
  documents: DocumentRow[],
  extractions: Extraction[],
): string {
  const docMap = new Map(documents.map((d) => [d.id, d]))
  const header = [
    'Account',
    'Document',
    'Doc Type',
    'Field',
    'AI Value',
    'Human Value',
    'Status',
    'Confidence',
    'Source',
    'Reviewed At',
  ]
  const rows = extractions.map((e) => {
    const doc = docMap.get(e.document_id)
    return [
      account.name,
      doc?.filename ?? '',
      doc?.doc_type ? DOC_TYPE_LABELS[doc.doc_type] : '',
      e.field_label,
      e.value,
      e.edited_value ?? '',
      e.status,
      String(Math.round(e.confidence * 100)),
      e.source_note ?? '',
      e.reviewed_at ?? '',
    ]
  })
  return [header, ...rows]
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n')
}

export function buildAnalysisReportHtml(
  account: Account,
  analysis: AccountAnalysis,
): string {
  const flags = analysis.flags
    .map(
      (f) =>
        `<tr><td>${f.severity}</td><td>${f.type}</td><td><strong>${f.title}</strong><br>${f.detail}</td><td>${(f.sourceDocuments ?? []).join(', ')}</td></tr>`,
    )
    .join('')
  const updates = analysis.suggested_updates
    .map(
      (u) =>
        `<tr><td>${u.field}</td><td>${u.suggestedValue}</td><td>${u.source}</td></tr>`,
    )
    .join('')
  const actions = analysis.action_items
    .map((a) => `<li><strong>[${a.priority}]</strong> ${a.title} — ${a.detail}</li>`)
    .join('')

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${account.name} — AgencyDesk Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.5; }
  h1 { font-size: 22px; } h2 { font-size: 16px; margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; margin-top: 8px; }
  th, td { border: 1px solid #e0e0e0; padding: 6px 8px; text-align: left; vertical-align: top; }
  th { background: #f5f5f5; }
  .summary { white-space: pre-wrap; background: #f9f9f9; padding: 12px; border-radius: 4px; font-size: 14px; }
  .meta { color: #666; font-size: 12px; }
</style></head><body>
<h1>${account.name}</h1>
<p class="meta">AgencyDesk AI Report · ${new Date(analysis.created_at).toLocaleString()}${analysis.model ? ` · ${analysis.model}` : ''}</p>
<h2>Summary</h2>
<div class="summary">${analysis.summary}</div>
${flags ? `<h2>Flags (${analysis.flags.length})</h2><table><tr><th>Severity</th><th>Type</th><th>Detail</th><th>Sources</th></tr>${flags}</table>` : ''}
${updates ? `<h2>Suggested CRM Updates</h2><table><tr><th>Field</th><th>Value</th><th>Source</th></tr>${updates}</table>` : ''}
${actions ? `<h2>Action Items</h2><ul>${actions}</ul>` : ''}
<p class="meta" style="margin-top:40px">Generated by AgencyDesk AI. Human review required before CRM updates.</p>
</body></html>`
}
